### ISSUE TITLE
Getting error when I add this

### ISSUE THREAD

**Issue by rzec-r7** [LonRes/ava-styled-components#1]
When I tried to add this, I get this error:

```
/repositories/my-project/node_modules/ava/lib/main.js:20
worker.setRunner(runner);
       ^

TypeError: worker.setRunner is not a function
    at Object.<anonymous> (/repositories/my-project/node_modules/ava/lib/main.js:20:8)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/repositories/my-project/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/repositories/my-project/node_modules/ava/index.js:7:19)
    at Module._compile (module.js:643:30)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/repositories/my-project/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

This is using ava 0.25.0 and Babel 6.

**Comment by Wildhoney** [comment]
I had the same issue &ndash; it only works with `ava@1.0.0-beta.x` versions. I'm using `1.0.0-beta.4` but it should work with `>= 1.0.0-beta.1 && <= 1.0.0-beta.4` 👍

**Comment by rzec-r7** [comment]
that unfortunate, not sure I am ready to have my production rely on Babel7 while it is still is beta

**Comment by Wildhoney** [comment]
Understandable. Maybe @imflavio could take a look to see what it'd take to support the latest stable version. Perhaps it's not too difficult.

**Comment by imflavio** [comment]
@rzec-r7 Does `parseStyles` fail when using directly inside the test file? Try without the setup step, if that doesn't work I'll look more into it

[create-react-app](https://github.com/facebook/create-react-app) is using Babel7 since [January](https://github.com/facebook/create-react-app/commit/1552949a3bce629de9e6fde1794e01c07226bf9c#diff-bbdb302ca59b70b47b0f90446cc507d2), not sure if this changes your mind

**Comment by rzec-r7** [comment]
@imflavio It fails when I include the setup code (and that is without even trying to use the custom `toJson` test method).

Also I am running Node 8.9.4 (let me know if there are any other details of my setup that would be helpful).

**Comment by imflavio** [comment]
Ok, I'll dig more into this issue, what are your styled-components/enzyme/enzyme-to-json versions?

**Comment by rzec-r7** [comment]
@imflavio 
styled-components = 3.1.6
enzyme = 3.3.0
enzyme-to-json = 3.3.0

**Comment by imflavio** [comment]
@rzec-r7 Okay played around with it. This bug has nothing todo with babel. The problem seems to be that `ava < 1.0.0` doesn't support "global" variables like:

```js
// setup.js
import test from 'ava';
import toJson from 'enzyme-to-json';
import parseStyles from 'ava-styled-components';

test.toJson = wrapper => parseStyles(toJson(wrapper));
```

Work around is either to upgrade the version, or export this toJson function so that it can be reused.
Example:

```js
// utils.js
import toJson from 'enzyme-to-json';
import parseStyles from 'ava-styled-components';

export const toJson = wrapper => parseStyles(toJson(wrapper));
```

```js
test.js
import test from 'ava';
import { mount } from 'enzyme';

import StyledComponent from './StyledComponent';
import { toJson } from './utils';

test('it should snapshot a styled component', t => {
    t.snapshot(toJson(mount(<StyledComponent />)))
});
```

Let me know if you find any other issues

**Comment by Wildhoney** [comment]
It's probably better as an export @imflavio &ndash; augmenting `ava` with `toJson` confuses ESLint:

```javascript
import test from 'ava';
import React from 'react';
import { mount } from 'enzyme';
import Index from '..';

test('it should snapshot a styled component', t => {
    const wrapper = mount(<Index />);
    t.snapshot(test.toJson(wrapper));
});
```

![''](https://i.imgur.com/NwYw75J.png)

**Comment by imflavio** [comment]
@Wildhoney Yeah.. I updated the readme with an easier usage example

**Comment by rzec-r7** [comment]
Yea, things work nicely with your suggestions, thanks.
